name: Deploy

on:
  push:
    branches:
      - main

env:
  ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_TOKEN }}

jobs:
  anaconda-deploy:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    defaults:
      run:
        shell: bash -l {0}
    steps:
    - uses: actions/checkout@v2
    - uses: conda-incubator/setup-miniconda@v2
      with:
          miniconda-version: "latest"
          auto-activate-base: true
          auto-update-conda: true
    - name: Setup conda tools
      run: |
          conda config --set always_yes yes
          conda config --set anaconda_upload yes
          conda install -c conda-forge conda-build anaconda-client conda-verify
    - name: Build tarbll
      run: |
          conda build --user usgs-astrogeology --label dev -c conda-forge -c tudat-team recipe/

  aws-docs-deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    steps:            
      - name: Set AWS credentials for upload
        uses: aws-actions/configure-aws-credentials@0e613a0980cbf65ed5b322eb7a1e075d28913a83
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
  
      - name: Upload to S3
        working-directory: ${{github.workspace}}/install
        run: |
          ls -l share/doc/SpiceQL/sphinx/
          aws s3 sync --delete share/doc/SpiceQL/sphinx/ s3://asc-public-docs/software_manuals/spiceql/
          